# Generated by Django 2.2.3 on 2019-07-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190724_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='last',
        ),
    ]
