# Generated by Django 2.2.3 on 2019-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190724_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
